name: testim-github-actions
on: [push]
jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g @testim/testim-cli 
      - run: testim --version
      - run: testim --test-plan "Demo Plan" --mode "appium" --token ${{ secrets.TESTIM_TOKEN }} --project ${{ secrets.TESTIM_PROJECTID }} --result-label ${{github.run_number}} --config-file myConfigV2.js

