name: testim-github-actions
on: [push]
jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
      - run: npm install -g @testim/testim-cli 
      - run: testim --version
      - run: testim --test-plan "Demo Plan" --mode "appium" --token "4bXNL1am4jLDGLXjsp1bBnJtCByOTfFcPdADgopyzMBR8pXix8" --project "RiuO9ZV8b7ZhHsXRPouY" --result-label ${{github.run_number}} --config-file mobileReportConfig.js

